openapi: 3.0.3
info:
  title: E-Commerce API
  version: 1.0.0
  description: API documentation for the e-commerce project.
paths:
  /api/login/:
    post:
      operationId: login_create
      tags:
      - login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Login'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: ''
  /api/orders/:
    get:
      operationId: orders_list
      tags:
      - orders
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
          description: ''
  /api/orders/{order_id}/:
    get:
      operationId: orders_retrieve
      parameters:
      - in: path
        name: order_id
        schema:
          type: integer
        required: true
      tags:
      - orders
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          description: ''
  /api/orders/{order_id}/cancel/:
    post:
      operationId: orders_cancel_create
      parameters:
      - in: path
        name: order_id
        schema:
          type: integer
        required: true
      tags:
      - orders
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          description: ''
  /api/orders/{order_id}/pay/:
    post:
      operationId: orders_pay_create
      parameters:
      - in: path
        name: order_id
        schema:
          type: integer
        required: true
      tags:
      - orders
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          description: ''
  /api/orders/create/:
    post:
      operationId: orders_create_create
      tags:
      - orders
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrder'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CreateOrder'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CreateOrder'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          description: ''
  /api/reddit/django/:
    get:
      operationId: reddit_django_retrieve
      tags:
      - reddit
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: Reddit posts from r/django.
        '503':
          description: Reddit is unavailable.
  /api/register/:
    post:
      operationId: register_create
      tags:
      - register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Register'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Register'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  username:
                    type: string
                  email:
                    type: string
          description: ''
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - ht
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/stores/:
    get:
      operationId: stores_list
      tags:
      - stores
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Store'
          description: ''
    post:
      operationId: stores_create
      tags:
      - stores
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Store'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Store'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Store'
        required: true
      security:
      - tokenAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Store'
          description: ''
  /api/stores/{store_id}/products/:
    get:
      operationId: stores_products_list
      parameters:
      - in: path
        name: store_id
        schema:
          type: integer
        required: true
      tags:
      - stores
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
          description: ''
    post:
      operationId: stores_products_create
      parameters:
      - in: path
        name: store_id
        schema:
          type: integer
        required: true
      tags:
      - stores
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Product'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      security:
      - tokenAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
  /api/stores/{store_id}/reviews/:
    get:
      operationId: stores_reviews_list
      parameters:
      - in: path
        name: store_id
        schema:
          type: integer
        required: true
      tags:
      - stores
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
          description: ''
    post:
      operationId: stores_reviews_create
      parameters:
      - in: path
        name: store_id
        schema:
          type: integer
        required: true
      tags:
      - stores
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Review'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Review'
        required: true
      security:
      - tokenAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
          description: ''
  /api/vendor/orders/:
    get:
      operationId: vendor_orders_list
      tags:
      - vendor
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
          description: ''
  /api/vendor/orders/{order_id}/:
    get:
      operationId: vendor_orders_retrieve
      parameters:
      - in: path
        name: order_id
        schema:
          type: integer
        required: true
      tags:
      - vendor
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          description: ''
  /api/vendor/orders/{order_id}/status/:
    patch:
      operationId: vendor_orders_status_partial_update
      parameters:
      - in: path
        name: order_id
        schema:
          type: integer
        required: true
      tags:
      - vendor
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedVendorOrderStatus'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedVendorOrderStatus'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedVendorOrderStatus'
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          description: ''
  /api/vendors/{vendor_id}/stores/:
    get:
      operationId: vendors_stores_list
      parameters:
      - in: path
        name: vendor_id
        schema:
          type: integer
        required: true
      tags:
      - vendors
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Store'
          description: ''
components:
  schemas:
    CreateOrder:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/CreateOrderItem'
      required:
      - items
    CreateOrderItem:
      type: object
      properties:
        product:
          type: integer
          minimum: 1
        quantity:
          type: integer
          minimum: 1
      required:
      - product
      - quantity
    Login:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
          writeOnly: true
      required:
      - password
      - username
    Order:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        buyer:
          type: integer
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        total:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
          readOnly: true
        status:
          allOf:
          - $ref: '#/components/schemas/OrderStatusEnum'
          readOnly: true
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
          readOnly: true
      required:
      - buyer
      - created_at
      - id
      - items
      - status
      - total
    OrderItem:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        product:
          type: integer
        product_name:
          type: string
          readOnly: true
        store_name:
          type: string
          readOnly: true
        quantity:
          type: integer
          maximum: 4294967295
          minimum: 0
          format: int64
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
      required:
      - id
      - price
      - product
      - product_name
      - quantity
      - store_name
    OrderStatusEnum:
      enum:
      - PENDING
      - PAID
      - COMPLETED
      - CANCELLED
      type: string
      description: |-
        * `PENDING` - Pending
        * `PAID` - Paid
        * `COMPLETED` - Completed
        * `CANCELLED` - Cancelled
    PatchedVendorOrderStatus:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/VendorOrderStatusStatusEnum'
    Product:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        store:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 200
        description:
          type: string
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        stock:
          type: integer
          maximum: 4294967295
          minimum: 0
          format: int64
        image:
          type: string
          format: uri
          nullable: true
      required:
      - id
      - name
      - price
      - store
    Register:
      type: object
      properties:
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          title: Email address
          oneOf:
          - type: string
            format: email
            maxLength: 254
          - type: string
            maxLength: 0
        password:
          type: string
          writeOnly: true
          minLength: 8
      required:
      - password
      - username
    Review:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        buyer:
          type: integer
          readOnly: true
        buyer_username:
          type: string
          readOnly: true
        product:
          type: integer
        product_name:
          type: string
          readOnly: true
        rating:
          type: integer
          maximum: 4294967295
          minimum: 0
          format: int64
        comment:
          type: string
        verified:
          type: boolean
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - buyer
      - buyer_username
      - comment
      - created_at
      - id
      - product
      - product_name
      - rating
      - verified
    Store:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        vendor:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 200
        description:
          type: string
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
          readOnly: true
      required:
      - created_at
      - description
      - id
      - name
      - products
      - updated_at
      - vendor
    VendorOrderStatusStatusEnum:
      enum:
      - PAID
      - COMPLETED
      - CANCELLED
      type: string
      description: |-
        * `PAID` - PAID
        * `COMPLETED` - COMPLETED
        * `CANCELLED` - CANCELLED
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
