"""
Django settings for the e-commerce project.

This module contains the configuration required to run the Django
application, including installed applications, middleware, database
configuration, authentication, static and media files, REST framework
settings, and API documentation.

Generated by 'django-admin startproject' using Django 6.1.

For more information on Django settings, see:
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see:
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()


# ---------------------------------------------------------------------------
# Base configuration
# ---------------------------------------------------------------------------

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------------
# Security and development settings
# ---------------------------------------------------------------------------

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-change-this-in-development",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# ---------------------------------------------------------------------------
# Application definition
# ---------------------------------------------------------------------------

# Applications enabled for this Django project.
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "drf_spectacular",
    "shop",
]


# Middleware responsible for processing HTTP requests and responses.
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# Root URL configuration for the project.
ROOT_URLCONF = "project.urls"


# Django template engine configuration.
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# WSGI application used to serve the Django project.
WSGI_APPLICATION = "project.wsgi.application"


# ---------------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------------

# Database configuration for the application.
#
# Database credentials should be supplied through environment variables
# rather than stored directly in source code.
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get("DB_NAME", "ecommerce_db"),
        "USER": os.environ.get("DB_USER", "root"),
        "PASSWORD": "RDWN25sammy#",
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "3306"),
    }
}


# ---------------------------------------------------------------------------
# Password validation
# ---------------------------------------------------------------------------

# Validators used to enforce password security requirements.
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation"
            ".UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation"
            ".MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation"
            ".CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation"
            ".NumericPasswordValidator"
        ),
    },
]


# ---------------------------------------------------------------------------
# Internationalization
# ---------------------------------------------------------------------------

# Default language used by the application.
LANGUAGE_CODE = "en-us"

# Default timezone used by the application.
TIME_ZONE = "UTC"

# Enable Django's internationalization system.
USE_I18N = True

# Enable timezone-aware datetime objects.
USE_TZ = True


# ---------------------------------------------------------------------------
# Static files
# ---------------------------------------------------------------------------

# URL used to serve static files such as CSS, JavaScript, and images.
STATIC_URL = "static/"

# Additional directories containing static files.
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# ---------------------------------------------------------------------------
# Email configuration
# ---------------------------------------------------------------------------

# Use Django's console email backend during development.
# Emails are displayed in the console instead of being sent.
MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}


# ---------------------------------------------------------------------------
# Authentication and user settings
# ---------------------------------------------------------------------------

# URL where unauthenticated users are redirected to log in.
LOGIN_URL = "/login/"

# URL users are redirected to after successful login.
LOGIN_REDIRECT_URL = "/"

# URL users are redirected to after logging out.
LOGOUT_REDIRECT_URL = "/"

# Django's built-in User model is used for authentication.
AUTH_USER_MODEL = "auth.User"


# ---------------------------------------------------------------------------
# Media files
# ---------------------------------------------------------------------------

# URL used to access uploaded media files.
MEDIA_URL = "/media/"

# Directory where uploaded media files are stored.
MEDIA_ROOT = BASE_DIR / "media"


# ---------------------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------------------

# Configuration for the Django REST Framework API.
REST_FRAMEWORK = {
    # Use token authentication for API requests.
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],

    # Use drf-spectacular to generate the OpenAPI schema.
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}


# ---------------------------------------------------------------------------
# API documentation
# ---------------------------------------------------------------------------

# Configuration for the automatically generated API documentation.
SPECTACULAR_SETTINGS = {
    "TITLE": "E-Commerce API",
    "DESCRIPTION": "API documentation for the e-commerce project.",
    "VERSION": "1.0.0",
}
