# Generated by Django 6.1 on 2026-09-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_order_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
