# Generated by Django 6.1 on 2026-09-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
