# Generated by Django 6.1 on 2026-09-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_remove_review_review_rating_1_to_5"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="product",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/"
            ),
        ),
    ]
