# Generated by Django 6.1 on 2026-09-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_remove_product_created_at_remove_product_stock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
