# Generated by Django 6.1 on 2026-09-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
